[_]
schema-version = "0.2"

[[build.env]]
name = "GOOGLE_FUNCTION_SIGNATURE_TYPE"
value = "http"

[[build.env]]
name = "GOOGLE_FUNCTION_TARGET"
value = "BQRFOllama"        

[io.buildpacks]
exclude = [
    "*_test.go",
    "*.tmp"
]